/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as ProtectedIndexRouteImport } from './app/_protected.index'
import { Route as workspaceLayoutRouteImport } from './app/(workspace)/_layout'
import { Route as authLayoutRouteImport } from './app/(auth)/_layout'
import { Route as workspaceJoinWorkspaceIdRouteImport } from './app/(workspace)/join.$workspaceId'
import { Route as authLayoutSignUpRouteImport } from './app/(auth)/_layout.sign-up'
import { Route as authLayoutSignInRouteImport } from './app/(auth)/_layout.sign-in'
import { Route as workspaceLayoutWorkspacesIdRouteImport } from './app/(workspace)/_layout.workspaces.$id'
import { Route as workspaceLayoutWorkspacesIdIndexRouteImport } from './app/(workspace)/_layout.workspaces.$id.index'
import { Route as workspaceLayoutWorkspacesIdMembersMemberIdRouteImport } from './app/(workspace)/_layout.workspaces.$id.members.$memberId'
import { Route as workspaceLayoutWorkspacesIdChannelChannelIdRouteImport } from './app/(workspace)/_layout.workspaces.$id.channel.$channelId'
import { Route as workspaceLayoutWorkspacesIdChannelChannelIdIndexRouteImport } from './app/(workspace)/_layout.workspaces.$id.channel.$channelId.index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const workspaceLayoutRoute = workspaceLayoutRouteImport.update({
  id: '/(workspace)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const workspaceJoinWorkspaceIdRoute =
  workspaceJoinWorkspaceIdRouteImport.update({
    id: '/(workspace)/join/$workspaceId',
    path: '/join/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authLayoutSignUpRoute = authLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutSignInRoute = authLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const workspaceLayoutWorkspacesIdRoute =
  workspaceLayoutWorkspacesIdRouteImport.update({
    id: '/workspaces/$id',
    path: '/workspaces/$id',
    getParentRoute: () => workspaceLayoutRoute,
  } as any)
const workspaceLayoutWorkspacesIdIndexRoute =
  workspaceLayoutWorkspacesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => workspaceLayoutWorkspacesIdRoute,
  } as any)
const workspaceLayoutWorkspacesIdMembersMemberIdRoute =
  workspaceLayoutWorkspacesIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => workspaceLayoutWorkspacesIdRoute,
  } as any)
const workspaceLayoutWorkspacesIdChannelChannelIdRoute =
  workspaceLayoutWorkspacesIdChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => workspaceLayoutWorkspacesIdRoute,
  } as any)
const workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute =
  workspaceLayoutWorkspacesIdChannelChannelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => workspaceLayoutWorkspacesIdChannelChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof authLayoutSignInRoute
  '/sign-up': typeof authLayoutSignUpRoute
  '/join/$workspaceId': typeof workspaceJoinWorkspaceIdRoute
  '/workspaces/$id': typeof workspaceLayoutWorkspacesIdRouteWithChildren
  '/workspaces/$id/': typeof workspaceLayoutWorkspacesIdIndexRoute
  '/workspaces/$id/channel/$channelId': typeof workspaceLayoutWorkspacesIdChannelChannelIdRouteWithChildren
  '/workspaces/$id/members/$memberId': typeof workspaceLayoutWorkspacesIdMembersMemberIdRoute
  '/workspaces/$id/channel/$channelId/': typeof workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof authLayoutSignInRoute
  '/sign-up': typeof authLayoutSignUpRoute
  '/join/$workspaceId': typeof workspaceJoinWorkspaceIdRoute
  '/workspaces/$id': typeof workspaceLayoutWorkspacesIdIndexRoute
  '/workspaces/$id/members/$memberId': typeof workspaceLayoutWorkspacesIdMembersMemberIdRoute
  '/workspaces/$id/channel/$channelId': typeof workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(workspace)/_layout': typeof workspaceLayoutRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/(auth)/_layout/sign-in': typeof authLayoutSignInRoute
  '/(auth)/_layout/sign-up': typeof authLayoutSignUpRoute
  '/(workspace)/join/$workspaceId': typeof workspaceJoinWorkspaceIdRoute
  '/(workspace)/_layout/workspaces/$id': typeof workspaceLayoutWorkspacesIdRouteWithChildren
  '/(workspace)/_layout/workspaces/$id/': typeof workspaceLayoutWorkspacesIdIndexRoute
  '/(workspace)/_layout/workspaces/$id/channel/$channelId': typeof workspaceLayoutWorkspacesIdChannelChannelIdRouteWithChildren
  '/(workspace)/_layout/workspaces/$id/members/$memberId': typeof workspaceLayoutWorkspacesIdMembersMemberIdRoute
  '/(workspace)/_layout/workspaces/$id/channel/$channelId/': typeof workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/join/$workspaceId'
    | '/workspaces/$id'
    | '/workspaces/$id/'
    | '/workspaces/$id/channel/$channelId'
    | '/workspaces/$id/members/$memberId'
    | '/workspaces/$id/channel/$channelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/join/$workspaceId'
    | '/workspaces/$id'
    | '/workspaces/$id/members/$memberId'
    | '/workspaces/$id/channel/$channelId'
  id:
    | '__root__'
    | '/_protected'
    | '/(auth)/_layout'
    | '/(workspace)/_layout'
    | '/_protected/'
    | '/(auth)/_layout/sign-in'
    | '/(auth)/_layout/sign-up'
    | '/(workspace)/join/$workspaceId'
    | '/(workspace)/_layout/workspaces/$id'
    | '/(workspace)/_layout/workspaces/$id/'
    | '/(workspace)/_layout/workspaces/$id/channel/$channelId'
    | '/(workspace)/_layout/workspaces/$id/members/$memberId'
    | '/(workspace)/_layout/workspaces/$id/channel/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
  workspaceLayoutRoute: typeof workspaceLayoutRouteWithChildren
  workspaceJoinWorkspaceIdRoute: typeof workspaceJoinWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(workspace)/_layout': {
      id: '/(workspace)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof workspaceLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspace)/join/$workspaceId': {
      id: '/(workspace)/join/$workspaceId'
      path: '/join/$workspaceId'
      fullPath: '/join/$workspaceId'
      preLoaderRoute: typeof workspaceJoinWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/sign-up': {
      id: '/(auth)/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authLayoutSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/sign-in': {
      id: '/(auth)/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authLayoutSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(workspace)/_layout/workspaces/$id': {
      id: '/(workspace)/_layout/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof workspaceLayoutWorkspacesIdRouteImport
      parentRoute: typeof workspaceLayoutRoute
    }
    '/(workspace)/_layout/workspaces/$id/': {
      id: '/(workspace)/_layout/workspaces/$id/'
      path: '/'
      fullPath: '/workspaces/$id/'
      preLoaderRoute: typeof workspaceLayoutWorkspacesIdIndexRouteImport
      parentRoute: typeof workspaceLayoutWorkspacesIdRoute
    }
    '/(workspace)/_layout/workspaces/$id/members/$memberId': {
      id: '/(workspace)/_layout/workspaces/$id/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/workspaces/$id/members/$memberId'
      preLoaderRoute: typeof workspaceLayoutWorkspacesIdMembersMemberIdRouteImport
      parentRoute: typeof workspaceLayoutWorkspacesIdRoute
    }
    '/(workspace)/_layout/workspaces/$id/channel/$channelId': {
      id: '/(workspace)/_layout/workspaces/$id/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/workspaces/$id/channel/$channelId'
      preLoaderRoute: typeof workspaceLayoutWorkspacesIdChannelChannelIdRouteImport
      parentRoute: typeof workspaceLayoutWorkspacesIdRoute
    }
    '/(workspace)/_layout/workspaces/$id/channel/$channelId/': {
      id: '/(workspace)/_layout/workspaces/$id/channel/$channelId/'
      path: '/'
      fullPath: '/workspaces/$id/channel/$channelId/'
      preLoaderRoute: typeof workspaceLayoutWorkspacesIdChannelChannelIdIndexRouteImport
      parentRoute: typeof workspaceLayoutWorkspacesIdChannelChannelIdRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface authLayoutRouteChildren {
  authLayoutSignInRoute: typeof authLayoutSignInRoute
  authLayoutSignUpRoute: typeof authLayoutSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutSignInRoute: authLayoutSignInRoute,
  authLayoutSignUpRoute: authLayoutSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface workspaceLayoutWorkspacesIdChannelChannelIdRouteChildren {
  workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute: typeof workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute
}

const workspaceLayoutWorkspacesIdChannelChannelIdRouteChildren: workspaceLayoutWorkspacesIdChannelChannelIdRouteChildren =
  {
    workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute:
      workspaceLayoutWorkspacesIdChannelChannelIdIndexRoute,
  }

const workspaceLayoutWorkspacesIdChannelChannelIdRouteWithChildren =
  workspaceLayoutWorkspacesIdChannelChannelIdRoute._addFileChildren(
    workspaceLayoutWorkspacesIdChannelChannelIdRouteChildren,
  )

interface workspaceLayoutWorkspacesIdRouteChildren {
  workspaceLayoutWorkspacesIdIndexRoute: typeof workspaceLayoutWorkspacesIdIndexRoute
  workspaceLayoutWorkspacesIdChannelChannelIdRoute: typeof workspaceLayoutWorkspacesIdChannelChannelIdRouteWithChildren
  workspaceLayoutWorkspacesIdMembersMemberIdRoute: typeof workspaceLayoutWorkspacesIdMembersMemberIdRoute
}

const workspaceLayoutWorkspacesIdRouteChildren: workspaceLayoutWorkspacesIdRouteChildren =
  {
    workspaceLayoutWorkspacesIdIndexRoute:
      workspaceLayoutWorkspacesIdIndexRoute,
    workspaceLayoutWorkspacesIdChannelChannelIdRoute:
      workspaceLayoutWorkspacesIdChannelChannelIdRouteWithChildren,
    workspaceLayoutWorkspacesIdMembersMemberIdRoute:
      workspaceLayoutWorkspacesIdMembersMemberIdRoute,
  }

const workspaceLayoutWorkspacesIdRouteWithChildren =
  workspaceLayoutWorkspacesIdRoute._addFileChildren(
    workspaceLayoutWorkspacesIdRouteChildren,
  )

interface workspaceLayoutRouteChildren {
  workspaceLayoutWorkspacesIdRoute: typeof workspaceLayoutWorkspacesIdRouteWithChildren
}

const workspaceLayoutRouteChildren: workspaceLayoutRouteChildren = {
  workspaceLayoutWorkspacesIdRoute:
    workspaceLayoutWorkspacesIdRouteWithChildren,
}

const workspaceLayoutRouteWithChildren = workspaceLayoutRoute._addFileChildren(
  workspaceLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
  workspaceLayoutRoute: workspaceLayoutRouteWithChildren,
  workspaceJoinWorkspaceIdRoute: workspaceJoinWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
